# Generated by Django 5.2.7 on 2025-10-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
